---
title: "Diabetes"
output: html_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
# Load required libraries
library(tidyverse)
library(rvest)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Clean dataset

```{r}
#Load Dataset
diabetes = 
  read_csv("Diabete datasets/diabetes_012_health_indicators_BRFSS2015.csv") |>
  janitor::clean_names() 
  


# Check for missing values
colSums(is.na(diabetes))
```

Data have `r nrow(diabetes)` records and `r ncol(diabetes)` variables. Each record contains an individual's BRFSS survey responses.

```{r}
diabetes %>%
  ggplot(aes(x = bmi, fill = diabetes_012, group = diabetes_012)) +
  geom_histogram(aes(y = ..density..), bins = 40, alpha = 0.6, color = "white") +
  geom_density(alpha = 0.3) +
  theme_minimal(base_size = 14) +
  labs(
    title = "BMI Distribution by Diabetes Status",
    x = "BMI",
    y = "Density",
    fill = "Diabetes Status"
  )

```

```{r}
library(DataExplorer)

# 전체 데이터 자동 프로파일링
create_report(
  data = diabetes,
  output_file = "diabetes_profile_report.html",
  output_dir = getwd(),  # 현재 폴더
  y = "diabetes_012"     # 타깃 변수 지정 가능
)


```

```{r}
library(SmartEDA)

ExpReport(
  data = diabetes,
  op_file = "diabetes_smartEDA_report.html",
  op_dir = getwd()
)
```

